export enum UploadStatusEnum {
  PENDING_UPLOAD = 'PENDING_UPLOAD',
  COMPLETE_UPLOAD = 'COMPLETE_UPLOAD',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}
